# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-01 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0013_auto_20190317_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=100)),
                ('phone_number1', models.IntegerField()),
                ('college_name1', models.CharField(max_length=100)),
                ('user_name1', models.CharField(max_length=100)),
                ('email1', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('easy_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number2', models.IntegerField()),
                ('college_name2', models.CharField(max_length=100)),
                ('user_name2', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('easy_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='user_f',
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(null=True, through='round2.Score', to='round2.User1'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='score',
            name='user1_f',
            field=models.ForeignKey(default=datetime.date(2020, 1, 1), on_delete=django.db.models.deletion.CASCADE, to='round2.User1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='user2_f',
            field=models.ForeignKey(default=datetime.date(2020, 1, 1), on_delete=django.db.models.deletion.CASCADE, to='round2.User2'),
            preserve_default=False,
        ),
    ]
