# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-01 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0016_auto_20200101_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user1_f',
            new_name='user_f',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user2_f',
        ),
    ]
