# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0018_auto_20200101_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=100)),
                ('phone_number1', models.IntegerField(default=0)),
                ('phone_number2', models.IntegerField(default=0)),
                ('college_name1', models.CharField(max_length=100)),
                ('college_name2', models.CharField(default='', max_length=100)),
                ('user_name1', models.CharField(max_length=100)),
                ('user_name2', models.CharField(default='', max_length=100)),
                ('email1', models.CharField(max_length=100)),
                ('email2', models.CharField(default='', max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('easy_counter', models.IntegerField(default=0)),
                ('cnt', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='user1_f',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user2_f',
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(null=True, through='round2.Score', to='round2.User'),
        ),
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.AddField(
            model_name='score',
            name='user_f',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='round2.User'),
            preserve_default=False,
        ),
    ]
