# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-04 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0019_auto_20200103_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cnt',
        ),
    ]
