# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round2', '0020_remove_user_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
    ]
